version: '3'

services:
  web:
    restart: always
    container_name: serviteca
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4200:4200
